import { expect } from "@playwright/test"
import { dirname, resolve } from "node:path"
import { Effect } from "effect"
import { testEffect } from "./effect-test"
import { createProject, launchApp, openPalette } from "./helpers"

testEffect("navigates project automations with the native rail, keyboard and hash history", (_fixtures, testInfo) => Effect.gen(function* () {
  const { win } = yield* launchApp(testInfo.config.configFile ?? "")
  const errors: string[] = []
  win.on("pageerror", (error) => errors.push(error.message))
  yield* Effect.gen(function* () {
    yield* Effect.tryPromise(() => win.setViewportSize({ width: 1440, height: 900 }))
    const rail = win.getByRole("button", { name: "Automations", exact: true })
    yield* Effect.tryPromise(() => expect(rail).toHaveAttribute("aria-disabled", "true"))
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "Collapse sidebar" }).focus())
    yield* Effect.tryPromise(() => win.keyboard.press("Tab"))
    yield* Effect.tryPromise(() => expect(rail).toBeFocused())
    yield* Effect.tryPromise(() => expect(win.getByRole("tooltip")).toHaveText("Select a project to open automations"))
    const initialUrl = win.url()
    yield* Effect.tryPromise(() => win.keyboard.press("Enter"))
    yield* Effect.tryPromise(() => expect(win).toHaveURL(initialUrl))
  })
  yield* createProject(win, "e2e-navigation-alpha")
  yield* createProject(win, "e2e-navigation-beta")
  yield* Effect.gen(function* () {
    yield* Effect.tryPromise(() => win.getByTestId("project-list").getByRole("link", { name: "e2e-navigation-alpha" }).click())
    const workspaceUrl = win.url()
    const rail = win.getByRole("button", { name: "Automations", exact: true })
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "Collapse sidebar" }).focus())
    yield* Effect.tryPromise(() => win.keyboard.press("Tab"))
    yield* Effect.tryPromise(() => expect(rail).toBeFocused())
    yield* Effect.tryPromise(() => expect(win.getByRole("tooltip")).toHaveText("Automations"))
    yield* Effect.tryPromise(() => expect(rail).toHaveCSS("outline-style", "solid"))
    yield* Effect.tryPromise(() => win.keyboard.press("Enter"))
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "Overview", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => expect(rail).toHaveAttribute("aria-current", "page"))
    yield* Effect.tryPromise(() => expect(win.getByRole("button", { name: "Active project: e2e-navigation-alpha" })).toBeVisible())
    yield* Effect.tryPromise(() => expect(win.getByRole("textbox", { name: "Search conversations" })).toBeVisible())
    for (const [label, suffix] of sections) {
      yield* Effect.tryPromise(() => win.getByRole("navigation", { name: "Automation pages" }).getByRole("button", { name: label, exact: true }).click())
      yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: label, exact: true })).toBeVisible())
      yield* Effect.tryPromise(() => expect(win).toHaveURL(`${workspaceUrl}/automations${suffix}`))
      yield* Effect.tryPromise(() => expect(win.getByRole("button", { name: label, exact: true })).toHaveAttribute("aria-current", "page"))
    }
    const historyUrl = win.url()
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "Sidebar three-zone shape, unread" }).click())
    yield* Effect.tryPromise(() => expect(win.getByRole("article")).toContainText("Rail holds devices, the panel holds the project switcher and the worktree inbox."))
    yield* Effect.tryPromise(() => expect(rail).not.toHaveAttribute("aria-current", "page"))
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "Back to automations" }).click())
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "History", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => expect(win).toHaveURL(historyUrl))
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "Active project: e2e-navigation-alpha" }).click())
    yield* Effect.tryPromise(() => win.getByRole("menuitem", { name: /e2e-navigation-beta/ }).click())
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "History", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => expect(win.getByRole("button", { name: "Active project: e2e-navigation-beta" })).toBeVisible())
    yield* Effect.tryPromise(() => expect(win).toHaveURL(/\/automations\/history$/))
    const betaHistoryUrl = win.url()
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "Sidebar three-zone shape, unread" }).click())
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "Switch sample device, active: This machine" }).click())
    yield* Effect.tryPromise(() => win.getByRole("menuitem", { name: /Field laptop/ }).click())
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "History", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => expect(win).toHaveURL(betaHistoryUrl))
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "Collapse sidebar" }).click())
    const pane = win.getByRole("region", { name: "Project and conversations", includeHidden: true })
    yield* Effect.tryPromise(() => expect(pane).toHaveAttribute("inert", ""))
    yield* Effect.tryPromise(() => rail.hover())
    yield* Effect.tryPromise(() => expect(win.getByRole("tooltip")).toHaveText("Automations"))
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "Expand sidebar" }).focus())
    yield* Effect.tryPromise(() => win.keyboard.press("Tab"))
    yield* Effect.tryPromise(() => expect(rail).toBeFocused())
    yield* Effect.tryPromise(() => win.keyboard.press("Space"))
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "Overview", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => expect(rail).toHaveAttribute("aria-current", "page"))
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "Expand sidebar" }).click())
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "Sidebar three-zone shape, unread" }).click())
    yield* Effect.tryPromise(() => rail.click())
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "Overview", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => win.screenshot({ path: screenshotPath(testInfo.config.configFile ?? "", "native-desktop.png") }))
    yield* Effect.tryPromise(() => win.getByRole("link", { name: "Back to workspace" }).click())
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "e2e-navigation-beta", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => win.goBack())
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "Overview", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => win.goForward())
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "e2e-navigation-beta", exact: true })).toBeVisible())
  })
  yield* openPalette(win)
  yield* Effect.gen(function* () {
    yield* Effect.tryPromise(() => win.getByRole("option", { name: "e2e-navigation-alpha", exact: true }).click())
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "e2e-navigation-alpha", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => win.evaluate(() => { window.location.hash = "/p/missing/automations/history" }))
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "Unknown project", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => expect(win.getByRole("link", { name: "Projects", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => expect(win.getByRole("navigation", { name: "Automation pages" })).toHaveCount(0))
    yield* Effect.tryPromise(() => expect(win.getByRole("button", { name: "Automations", exact: true })).toHaveAttribute("aria-disabled", "true"))
    expect(errors).toEqual([])
  })
}))

testEffect("closes the native mobile Sheet after automation and project selection and restores focus", (_fixtures, testInfo) => Effect.gen(function* () {
  const { win } = yield* launchApp(testInfo.config.configFile ?? "")
  yield* createProject(win, "e2e-mobile-alpha")
  yield* createProject(win, "e2e-mobile-beta")
  yield* Effect.gen(function* () {
    yield* Effect.tryPromise(() => win.getByTestId("project-list").getByRole("link", { name: "e2e-mobile-alpha" }).click())
    yield* Effect.tryPromise(() => win.setViewportSize({ width: 390, height: 844 }))
    const trigger = win.getByRole("button", { name: "Open sidebar" })
    yield* Effect.tryPromise(() => trigger.click())
    const sheet = win.getByRole("dialog", { name: "Sidebar", exact: true })
    yield* Effect.tryPromise(() => sheet.getByRole("button", { name: "Automations", exact: true }).click())
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "Overview", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => expect(sheet).toHaveCount(0))
    yield* Effect.tryPromise(() => expect(trigger).toBeFocused())
    yield* Effect.tryPromise(() => win.getByRole("button", { name: "History", exact: true }).click())
    yield* Effect.tryPromise(() => trigger.click())
    yield* Effect.tryPromise(() => sheet.getByRole("button", { name: "Sidebar three-zone shape, unread" }).click())
    yield* Effect.tryPromise(() => expect(win.getByRole("button", { name: "Back to automations" })).toBeVisible())
    yield* Effect.tryPromise(() => expect(trigger).toBeFocused())
    yield* Effect.tryPromise(() => trigger.click())
    yield* Effect.tryPromise(() => expect(sheet.getByRole("button", { name: "Automations", exact: true })).not.toHaveAttribute("aria-current", "page"))
    yield* Effect.tryPromise(() => sheet.getByRole("button", { name: "Active project: e2e-mobile-alpha" }).click())
    yield* Effect.tryPromise(() => win.getByRole("menuitem", { name: /e2e-mobile-beta/ }).click())
    yield* Effect.tryPromise(() => expect(sheet).toHaveCount(0))
    yield* Effect.tryPromise(() => expect(trigger).toBeFocused())
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "History", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => trigger.click())
    yield* Effect.tryPromise(() => sheet.getByRole("button", { name: "Automations", exact: true }).click())
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "Overview", exact: true })).toBeVisible())
    yield* Effect.tryPromise(() => expect(trigger).toBeFocused())
    yield* Effect.tryPromise(() => trigger.click())
    yield* Effect.tryPromise(() => win.keyboard.press("Escape"))
    yield* Effect.tryPromise(() => expect(sheet).toHaveCount(0))
    yield* Effect.tryPromise(() => expect(trigger).toBeFocused())
    yield* Effect.tryPromise(() => win.screenshot({ path: screenshotPath(testInfo.config.configFile ?? "", "native-mobile.png") }))
    yield* Effect.tryPromise(() => win.setViewportSize({ width: 320, height: 740 }))
    yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "Overview", exact: true })).toBeVisible())
    expect(yield* Effect.tryPromise(() => win.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth))).toBe(true)
    yield* Effect.tryPromise(() => expect(win.getByRole("alert")).toHaveCount(0))
  })
}))

testEffect("reopens native automation history after reloading its hash URL", (_fixtures, testInfo) => Effect.gen(function* () {
  const { win } = yield* launchApp(testInfo.config.configFile ?? "")
  yield* createProject(win, "e2e-reload")
  yield* Effect.tryPromise(() => win.getByTestId("project-list").getByRole("link", { name: "e2e-reload" }).click())
  yield* Effect.tryPromise(() => win.getByRole("button", { name: "Automations", exact: true }).click())
  yield* Effect.tryPromise(() => win.getByRole("button", { name: "History", exact: true }).click())
  yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "History", exact: true })).toBeVisible({ timeout: 15_000 }))
  const historyUrl = win.url()
  yield* Effect.tryPromise(() => win.reload())
  yield* Effect.tryPromise(() => win.screenshot({ path: screenshotPath(testInfo.config.configFile ?? "", "native-hash-reload.png") }))
  yield* Effect.tryPromise(() => expect(win).toHaveURL(historyUrl))
  yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "History", exact: true })).toBeVisible({ timeout: 15_000 }))
}))

const sections = [
  ["Overview", ""],
  ["Integrations", "/integrations"],
  ["Routine setup", "/routines/new"],
  ["History", "/history"]
] as const

const screenshotPath = (configFile: string, name: string) =>
  resolve(dirname(configFile), "../../../.tmp/implement-t11-20261002", name)
