import { expect } from "@playwright/test"
import { Effect } from "effect"
import { testEffect } from "./effect-test"
import { createProject, launchApp } from "./helpers"

testEffect("resizes the desktop sidebar and keeps only settings at the bottom", (_fixtures, testInfo) => Effect.gen(function* () {
  const { win } = yield* launchApp(testInfo.config.configFile ?? "")
  const launchUrl = win.url()
  yield* Effect.tryPromise(() => win.setViewportSize({ width: 1024, height: 800 }))
  yield* Effect.tryPromise(() => expect(win.locator("html")).toHaveClass(/dark/))
  const device = win.getByRole("button", { name: "Switch device, active: This machine" })
  const rail = win.locator('[data-slot="sidebar"]').filter({ has: device }).last()
  const settings = win.getByRole("button", { name: "Settings", exact: true })
  const automation = win.getByRole("button", { name: "Automations", exact: true })
  yield* Effect.tryPromise(() => expect(rail).not.toContainText(/sample/i))
  yield* Effect.tryPromise(() => expect.poll(() => settings.evaluate((element) => 800 - element.getBoundingClientRect().bottom)).toBeLessThan(16))
  yield* Effect.tryPromise(() => expect.poll(() => automation.evaluate((element) => element.getBoundingClientRect().y)).toBeLessThan(140))

  const handle = win.getByRole("separator", { name: "Resize sidebar" })
  yield* Effect.tryPromise(() => expect(handle).toBeVisible())
  const start = yield* Effect.tryPromise(() => handle.boundingBox())
  expect(start).not.toBeNull()
  yield* Effect.tryPromise(() => win.mouse.move(start!.x + start!.width / 2, 300))
  yield* Effect.tryPromise(() => win.mouse.down())
  yield* Effect.tryPromise(() => win.mouse.move(start!.x + 96, 300))
  yield* Effect.tryPromise(() => win.mouse.up())
  const resizedWidth = Number(yield* Effect.tryPromise(() => handle.getAttribute("aria-valuenow")))
  expect(resizedWidth).toBeGreaterThan(380)
  yield* Effect.tryPromise(() => expect.poll(() => win.locator('[data-slot="sidebar-container"]').evaluate((element, expected) => Math.abs(element.getBoundingClientRect().width - expected), resizedWidth)).toBeLessThan(1))
  yield* Effect.tryPromise(() => expect.poll(() => win.locator('[data-slot="sidebar-inset"]').evaluate((element, expected) => Math.abs(element.getBoundingClientRect().x - expected), resizedWidth)).toBeLessThan(1))

  yield* Effect.tryPromise(() => win.getByRole("button", { name: "Collapse sidebar" }).click())
  yield* Effect.tryPromise(() => expect(handle).toHaveCount(0))
  yield* Effect.tryPromise(() => expect.poll(() => rail.evaluate((element) => Math.abs(element.getBoundingClientRect().width - 48))).toBeLessThan(1))
  yield* Effect.tryPromise(() => win.getByRole("button", { name: "Expand sidebar" }).click())
  yield* Effect.tryPromise(() => expect(handle).toHaveAttribute("aria-valuenow", String(resizedWidth)))
  yield* Effect.tryPromise(() => handle.focus())
  yield* Effect.tryPromise(() => win.keyboard.press("End"))
  yield* Effect.tryPromise(() => expect(handle).toHaveAttribute("aria-valuenow", "480"))
  yield* Effect.tryPromise(() => win.setViewportSize({ width: 768, height: 800 }))
  yield* Effect.tryPromise(() => expect(handle).toHaveAttribute("aria-valuenow", "448"))
  yield* Effect.tryPromise(() => expect.poll(() => win.locator('[data-slot="sidebar-inset"]').evaluate((element) => element.getBoundingClientRect().width)).toBeGreaterThan(319))
  yield* Effect.tryPromise(() => expect.poll(() => win.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true))
  yield* Effect.tryPromise(() => win.screenshot({ path: testInfo.outputPath("sidebar-desktop-dark.png"), animations: "disabled" }))
  yield* Effect.tryPromise(() => win.getByRole("button", { name: "Settings", exact: true }).click())
  yield* Effect.tryPromise(() => win.getByRole("button", { name: "Appearance", exact: true }).click())
  yield* Effect.tryPromise(() => win.getByRole("switch", { name: "Dark mode" }).click())
  yield* Effect.tryPromise(() => expect(win.locator("html")).not.toHaveClass(/dark/))
  yield* Effect.tryPromise(() => win.goto(launchUrl))
  yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: /Projects/ })).toBeVisible())
  yield* Effect.tryPromise(() => win.screenshot({ path: testInfo.outputPath("theme-after-reload.png"), animations: "disabled" }))
  yield* Effect.tryPromise(() => win.getByRole("button", { name: "Settings", exact: true }).click())
  yield* Effect.tryPromise(() => win.getByRole("button", { name: "Appearance", exact: true }).click())
  yield* Effect.tryPromise(() => expect(win.getByRole("switch", { name: "Dark mode" })).not.toBeChecked())
  yield* Effect.tryPromise(() => expect(win.locator("html")).not.toHaveClass(/dark/))
  yield* Effect.tryPromise(() => win.getByRole("button", { name: "Back", exact: true }).click())
  yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: /Projects/ })).toBeVisible())
  yield* Effect.tryPromise(() => win.screenshot({ path: testInfo.outputPath("sidebar-desktop-light.png"), animations: "disabled" }))
}))

testEffect("keeps the narrow drawer usable and dismisses it by clicking outside", (_fixtures, testInfo) => Effect.gen(function* () {
  const { win } = yield* launchApp(testInfo.config.configFile ?? "")
  yield* createProject(win, "sidebar-test-project")
  for (const width of [390, 320]) {
    yield* Effect.tryPromise(() => win.setViewportSize({ width, height: 800 }))
    const opener = win.getByRole("button", { name: "Open sidebar" })
    yield* Effect.tryPromise(() => opener.click())
    const drawer = win.getByRole("dialog", { name: "Sidebar", exact: true })
    yield* Effect.tryPromise(() => expect(drawer).toBeVisible())
    yield* Effect.tryPromise(() => expect(drawer.getByRole("button", { name: "Close", exact: true })).toHaveCount(0))
    yield* Effect.tryPromise(() => expect(drawer).not.toContainText(/sample/i))
    yield* Effect.tryPromise(() => expect(drawer).toHaveCSS("animation-duration", "0.2s"))
    const device = drawer.getByRole("button", { name: "Switch device, active: This machine" })
    yield* Effect.tryPromise(() => expect.poll(() => device.evaluate((element) => element.getBoundingClientRect().y)).toBeLessThan(16))
    const rail = drawer.locator('[data-slot="sidebar"]').filter({ has: win.getByRole("button", { name: "Switch device, active: This machine" }) }).last()
    yield* Effect.tryPromise(() => expect.poll(() => rail.evaluate((element) => Math.abs(element.getBoundingClientRect().width - 48))).toBeLessThan(1))
    const pane = drawer.locator('[aria-label="Project and conversations"]')
    yield* Effect.tryPromise(() => expect.poll(() => pane.evaluate((element) => element.getBoundingClientRect().width)).toBeGreaterThan(240))
    yield* Effect.tryPromise(() => expect.poll(() => pane.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true))
    yield* Effect.tryPromise(() => expect(drawer.getByRole("textbox", { name: "Search conversations" })).toBeVisible())
    yield* Effect.tryPromise(() => win.screenshot({ path: testInfo.outputPath(`sidebar-mobile-${width}.png`), animations: "disabled" }))
    yield* Effect.tryPromise(() => win.mouse.click(width - 4, 400))
    yield* Effect.tryPromise(() => expect(drawer).toHaveCount(0))
    yield* Effect.tryPromise(() => expect(opener).toBeFocused())
  }

  yield* Effect.tryPromise(() => win.getByRole("button", { name: "Open sidebar" }).click())
  yield* Effect.tryPromise(() => win.getByRole("button", { name: "Automations", exact: true }).click())
  yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "Automations", exact: true })).toBeVisible())
  yield* Effect.tryPromise(() => expect(win.getByRole("dialog", { name: "Sidebar", exact: true })).toHaveCount(0))
  yield* Effect.tryPromise(() => win.getByRole("link", { name: "Open automations for sidebar-test-project" }).click())
  yield* Effect.tryPromise(() => expect(win.getByRole("heading", { name: "Overview", exact: true })).toBeVisible())
  yield* Effect.tryPromise(() => win.emulateMedia({ reducedMotion: "reduce" }))
  yield* Effect.tryPromise(() => win.getByRole("button", { name: "Open sidebar" }).click())
  const drawer = win.getByRole("dialog", { name: "Sidebar", exact: true })
  yield* Effect.tryPromise(() => expect(drawer).toHaveCSS("animation-name", "none"))
  yield* Effect.tryPromise(() => win.keyboard.press("Escape"))
  yield* Effect.tryPromise(() => expect(drawer).toHaveCount(0))
}))
